### ISSUE TITLE
Error message about loading theme plastik

### ISSUE THREAD

**Issue by RedFantom** [RedFantom/ttkthemes#12]
The theme `plastik` produces an error message when loaded. The theme has done this since I started using it first in a separate program in the assets folder, but it still persists in the library. I have looked for the problem multiple times, but it will require some very deep digging to fix. Or I'm missing something, perhaps. Anyway, it requires attention.

**Comment by RedFantom** [comment]
This was actually fixed by removing the `pkgINdex.tcl` and `plastik.tcl` files from `ttkthemes/themes/plastik/plastik`.

**Comment by maicol07** [comment]
Hi, this problem persists and I haven't that files in the specified folder...
