### ISSUE TITLE
Update theme files for appropriate Treeview fieldbackground colors

### ISSUE THREAD

**Issue by RedFantom** [RedFantom/ttkthemes#18]
This question follows from #15. The Treeview widget displays a white area under the tree elements:
![tree](https://user-images.githubusercontent.com/18505570/39082930-bbee0ba8-4563-11e8-98c0-987aaf696384.png)

It should be investigated whether this area can be modified by the theme, to make it more appropriately coloured.

**Comment by Akuli** [comment]
Maybe this can be useful?

```
wish8.6 [~]ttk::style layout Treeview 
Treeview.field -sticky nswe -border 1 -children {Treeview.padding -sticky nswe -children {Treeview.treearea -sticky nswe}}
wish8.6 [~]ttk::style element options Treeview.treearea
wish8.6 [~]ttk::style element options Treeview.field
-fieldbackground -borderwidth
wish8.6 [~]
```

I have never actually created a ttk theme, so I don't know what to check next.

**Comment by Akuli** [comment]
Any updates on this? I use the black theme with an application that uses a treeview almost every day, and the white area is kind of annoying.

**Comment by RedFantom** [comment]
Now there is :smile:

**Comment by Akuli** [comment]
Awesome :D

**Comment by Akuli** [comment]
This looks soooo much better. Thanks!

**Comment by RedFantom** [comment]
@Akuli I'm glad you like it!

Merged for next release.
