### ISSUE TITLE
Upload new version on PyPi

### ISSUE THREAD

**Issue by maicol07** [RedFantom/ttkthemes#25]
Hi, could you upload new version on PiPy?
Thanks

**Comment by RedFantom** [comment]
Of course! I initiated the wheel building process by tagging a new version, and after that I was travelling, so I couldn't yet. I will get to it as soon as possible now I have access to a computer again.

**Comment by RedFantom** [comment]
I decided to check why the CI didn't complete last night, and as it turns out the last build of a commit was queued for over 21 hours. Building of the new version should initiate shortly.

**Comment by RedFantom** [comment]
Published!
