### ISSUE TITLE
Missing Listbox?

### ISSUE THREAD

**Issue by oversoul** [RedFantom/ttkthemes#37]
is it just me or the listbox doesnt exist anywhere?

thank you.

**Comment by RedFantom** [comment]
As you can read in the [ttk documentation](https://docs.python.org/3/library/tkinter.ttk.html), the `ttk` module does not include a `Listbox` widget.

**Comment by Akuli** [comment]
Maybe I should clarify a bit: @oversoul , you should use `Treeview` instead. It can be used just like a `Listbox` if you insert all items under the root item.
