### ISSUE TITLE
black theme: current notebook tab is same color as other tabs

### ISSUE THREAD

**Issue by Akuli** [RedFantom/ttkthemes#46]
![aaaaa](https://user-images.githubusercontent.com/18505570/44618335-97bda780-a87c-11e8-8d3f-ef218b385f31.png)

It is very hard to tell which tab is selected. This is especially annoying because I have a ttk program that I use every day, and I really like the `black` theme otherwise.

**Comment by RedFantom** [comment]
For next time: These things may be reported in #44 .

This indeed looks like a serious UI issue. As `black` is based on `clam`, this might require more than just changing the `background` option of the `Notebook.Tab` style for the `selected` state.

**Comment by Akuli** [comment]
This is awesome!
