### ISSUE TITLE
_tkinter.TclError: couldn't connect to display "arc"

### ISSUE THREAD

**Issue by crinny** [RedFantom/ttkthemes#55]
I see `_tkinter.TclError: couldn't connect to display "arc"` error when trying to run example code from ReadTheDocs. Here it is:
`from tkinter import ttk  # Normal Tkinter.* widgets are not themed!
from ttkthemes import ThemedTk

window = ThemedTk("arc")
ttk.Button(window, text="Quit", command=window.destroy).pack()
window.mainloop()`

I am using Python 3.6.7 and latest ttkthemes. My OS is Ubuntu 18.04

**Comment by RedFantom** [comment]
My apologies! There is a mistake in the example code, it ought to be a keyword argument, so not
```python
window = ThemedTk("arc")
``` 
but instead:
```python
window = ThemedTk(theme="arc")
```

I will fix the documentation as soon as I can.

**Comment by crinny** [comment]
Thanks!
