### ISSUE TITLE
Is ttkthemes working with pyinstaller?

### ISSUE THREAD

**Issue by crinny** [RedFantom/ttkthemes#56]
I am trying to make executable out of Tkinter app with ttkthemes on Windows 7 (Python 3.6.7, system-wide installation) using pyinstaller, but i get error like this: `FileNotFoundError: 'C:/super/legit/path/ttkthemes'`. On Ubuntu 18.04 all works perfect.

**Comment by Akuli** [comment]
Do tkinter programs that don't use ttkthemes work? Have you tried `--hidden-import=ttkthemes` or other things [here](https://pyinstaller.readthedocs.io/en/v3.3.1/when-things-go-wrong.html)? If you get this to work, tell about it here so that it can be perhaps added to ttkthemes documentation.

**Comment by Akuli** [comment]
I got this to work.

1. Create a pyinstaller spec file

    ```
    pyi-makespec --onefile --windowed myprogram.py
    ```

    this will create `myprogram.spec`

2. Figure out where ttkthemes is installed

    ```python3
    >>> import ttkthemes
    >>> print(ttkthemes.__path__[0])
    ```

3. open the spec file in an editor and replace `datas=[]` with this:

    ```
    datas=[
        ('TTKTHEMESPATH\\advanced', 'ttkthemes\\advanced'),
        ('TTKTHEMESPATH\\gif', 'ttkthemes\\gif'),
        ('TTKTHEMESPATH\\png', 'ttkthemes\\png'),
        ('TTKTHEMESPATH\\themes', 'ttkthemes\\themes'),
    ]
    ```

    where `TTKTHEMESPATH` is `ttkthemes.__path__[0]` and `advanced`, `gif`, `png` and `themes` are all its subdirectories

4. run `pyinstaller myprogram.spec`

Ideally there would be a pyinstaller hook that does this automatically, or at least this should be documented. You can also write a script that does all these things.

**Comment by RedFantom** [comment]
This is an issue that I have encountered before in one of my own programs. I created a script for building a release and made it copy over the full `ttkthemes` package and all its subdirectories to the folder the executable was in.

The solution described by @Akuli is the better one though. If it works properly I will put in the documentation. If there is a more proper solution that can be implemented within the ttkthemes package, then I want to include it, but as far as I know there needs to be some sort of custom hook included with pyinstaller, and it's not that high on the priority list.

**Comment by crinny** [comment]
Still having `FileNotFoundError: [Errno 2] No such file or directory: '/tmp/_MEIyVgZlQ/ttkthemes'` after all these manipulations.

**Comment by RedFantom** [comment]
To make this easier to do, I created a PyInstaller hook for `ttkthemes` in a fork of the repository ([`6cc26f5`](https://github.com/RedFantom/pyinstaller/commit/6cc26f568082516a0e9776ce0134697514f105eb)). Currently, I am not in a position to test on a platform other than Linux, and I would like to make sure that it is the correct way of doing this before submitting a PR. If you are still interested in solving this issue permanently, @crinny , could you test it for me under Windows to make sure?

**Comment by Akuli** [comment]
You can download a free windows virtual machine from microsoft that expires in 30 days. https://developer.microsoft.com/en-us/microsoft-edge/tools/vms/

**Comment by crinny** [comment]
> 
> 
> To make this easier to do, I created a PyInstaller hook for `ttkthemes` in a fork of the repository ([`6cc26f5`](https://github.com/RedFantom/pyinstaller/commit/6cc26f568082516a0e9776ce0134697514f105eb)). Currently, I am not in a position to test on a platform other than Linux, and I would like to make sure that it is the correct way of doing this before submitting a PR. If you are still interested in solving this issue permanently, @crinny , could you test it for me under Windows to make sure?

I will test it later

**Comment by RedFantom** [comment]
The PR for pyinstaller has been merged by the maintainer, thus I will close this issue. I expected the hook to be included in the next version of `pyinstaller`, making `ttkthemes` work out of the box.
