### ISSUE TITLE
Styling Tkinter dialogs

### ISSUE THREAD

**Issue by crinny** [RedFantom/ttkthemes#57]
I want to use `tkinter.simpledialog.askstring` in my code, but it is not styled by ttkthemes. Looks like there is no such widget in `tkinter.ttk`. How can i reaplce it or style?

**Comment by RedFantom** [comment]
It is correct that ttk does not theme the dialogs created by functions in the modules `filedialog`, `simpledialog` and `messagebox`. Their exact behaviour is platform-dependent. On Windows, the native functions are used for the dialogs as far as that is possible.

If you want to use a dialog that is styled, you will have to roll your own. Depending on the exact options you would like to implement, it can be really easy. For alternative file dialogs, you can also use the excellent [tkFileBrowser](https://github.com/j4321/tkFileBrowser).

An example of a custom dialog may be found [here](https://github.com/RedFantom/gsf-parser/blob/master/toplevels/choice.py), though there may be better examples out there.

**Comment by Akuli** [comment]
On some platforms, `tkinter.messagedialog` things get styled because they use ttk widgets. `simpledialog` is old non-Ttk code (it's even older than I am! see the source code), so don't expect it to be modern or nice.

**Comment by Akuli** [comment]
If you're looking for a nicer alternative to `simpledialog`, here's one I have made:

```python3
import tkinter as tk
from tkinter import ttk


class _EntryDialog:

    def __init__(self, title, text, validator,
                 initial_value, parent):
        self.validator = validator

        self.window = tk.Toplevel()
        self.window.title(title)
        self.window.protocol('WM_DELETE_WINDOW', self.on_cancel)
        if parent is not None:
            self.window.transient(parent)

        content = ttk.Frame(self.window)
        content.pack(fill='both', expand=True)

        self.var = tk.StringVar()

        ttk.Label(content, text=text).grid(row=0, column=0, columnspan=2)
        entry = ttk.Entry(content, textvariable=self.var)
        entry.grid(row=1, column=0, columnspan=2)
        entry.bind('<Return>', (lambda event: self.on_ok()))
        entry.bind('<Escape>', (lambda event: self.on_cancel()))

        self.ok_button = ttk.Button(content, text="OK", command=self.on_ok)
        self.ok_button.grid(row=3, column=0)
        ttk.Button(content, text="Cancel", command=self.on_cancel).grid(
            row=3, column=1)

        content.grid_rowconfigure(0, weight=1)
        content.grid_rowconfigure(2, weight=1)
        content.grid_columnconfigure(0, weight=1)
        content.grid_columnconfigure(1, weight=1)

        self.result = None
        self.var.trace('w', self.on_var_changed)
        self.var.set(initial_value)
        self.on_var_changed(self.var)   # TODO: is this needed?

        self.window.geometry('300x150')
        entry.focus()
        entry.select_range(0, 'end')

    def on_var_changed(self, *junk):
        result = self.var.get()
        try:
            self.result = self.validator(result)
            self.ok_button['state'] = 'normal'
        except ValueError:
            self.result = None
            self.ok_button['state'] = 'disabled'

    def on_ok(self):
        # this state check is needed because <Return> is bound to this, and
        # that binding can run even if the button is disabled
        # str() is needed because tkinter is awesome, isn't it
        if str(self.ok_button['state']) == 'normal':
            self.window.destroy()

    def on_cancel(self):
        self.result = None
        self.window.destroy()

    def run(self):
        self.window.wait_window()
        return self.result


def ask_string(title, text, *, validator=str, initial_value='', parent=None):
    return _EntryDialog(title, text, validator, initial_value, parent).run()


# example:
def len3_validator(value):
    if len(value) != 3:
        raise ValueError
    return value


root = tk.Tk()
answer = ask_string("Question", "Enter a string of 3 characters:",
                    validator=len3_validator, parent=root)
print("answer:", answer)
```

**Comment by RedFantom** [comment]
Yes, the source code is from 1997. Perhaps it would be an idea to update the source for ttk usage and see if it can be merged back into CPython.

In any case, you can also check out the [ttkSimpleDialog](https://pypi.org/project/ttkSimpleDialog/) package on PyPI. I have not tested it myself, but it looks to be exactly what you want.

**Comment by RedFantom** [comment]
@crinny Given the inactivity on this issue, I will close it. If you have any further questions about this particular topic, feel free to reopen the issue. If you have questions about something else, don't hesitate to open a new issue.
