### ISSUE TITLE
ImportError upon running example.py

### ISSUE THREAD

**Issue by noval102200** [RedFantom/ttkthemes#59]
when i run the example.py.error occur below:
 
 from mss import mss
ImportError: No module named mss

**Comment by RedFantom** [comment]
If you try to run the screenshot functionality of the example, an additional dependency of `python-mss` is required. You can install it with `pip install mss`.

**Comment by noval102200** [comment]
when i use threading ,app will print the last mttkinter debug message when the app exit:
('Marshalling event:', 'call', ('info', 'exists', 'PY_VAR9'), {})
if i'm not use threading,message above will not print.

**Comment by noval102200** [comment]
may be i have found where the problem happend.
in the file "example.py" of mttkinter.
quit = Button(root, text="QUIT", command=**root.destroy**)

if i replace command ="root.destroy" with command ="root.quit" 
when i run example.py ,the program will blocked and have no response when i press quit button.
