### ISSUE TITLE
ThemedStyle.theme_use doesn't work without arguments

### ISSUE THREAD

**Issue by Akuli** [RedFantom/ttkthemes#6]
`ttk.Style().theme_use()` can be called with no arguments to check which ttk theme is currently being used, but `ttkthemes.ThemedStyle` doesn't support it.

```python
>>> from tkinter import ttk
>>> import ttkthemes
>>> ttk.Style().theme_use()
'default'
>>> ttkthemes.ThemedStyle().theme_use()
Traceback (most recent call last):
  ...
TypeError: set_theme() missing 1 required positional argument: 'theme_name'
>>>
```

Of course, this is easy to fix with e.g. `style.tk.eval("return $ttk::currentTheme")` (yes, I got this from tkinter's code), but it would be nice if the `theme_use` method was compatible with the `theme_use` it overrides (instead of just aliasing it to `set_theme`).

**Comment by Akuli** [comment]
I created [a pull request](https://github.com/RedFantom/ttkthemes/pull/7) about this.

**Comment by RedFantom** [comment]
I'd prefer this issue remains open while the PR is not merged.
