### ISSUE TITLE
ttkthemes not working on python 3.7

### ISSUE THREAD

**Issue by krishabh1998** [RedFantom/ttkthemes#60]
I'm getting this error even I have installed the ttkthemes module from inside of pycharm also and through cmd of windows also but still not working

error-from ttkthemes import ThemedTk
ModuleNotFoundError: No module named 'ttkthemes'

**Comment by Akuli** [comment]
How did you install ttkthemes?

**Comment by krishabh1998** [comment]
> 
> 
> How did you install ttkthemes?

Installed in pycharm by going into plugins and download it
