### ISSUE TITLE
Installation error on Ubuntu 16.04

### ISSUE THREAD

**Issue by ndv99** [RedFantom/ttkthemes#9]
Tried to install the module in Ubuntu 16.04 as stated in the "Installation" section of the wiki, but got this error:

`error: can't copy 'ttkthemes/themes/radiance': doesn't exist or not a regular file`

Not sure what might be causing it.

**Comment by RedFantom** [comment]
Could you provide me with some more information that might help me reproducing this issue?
- What version of Python are you using? (Python 2.7 if you really copy the command in the wiki)
- Is your `pip` installation up-to-date? (`python -m pip install --update pip`, or `python3` when using Python 3)

**Comment by ndv99** [comment]
@RedFantom Sure thing, probably should've put that in the original post, my bad.

Python version: 3.5, running in a virtual environment
Pip version: 9.0.1

**Comment by RedFantom** [comment]
@ndv99 Thank you. Could you try also updating `setuptools`?

**Comment by ndv99** [comment]
@RedFantom updated `setuptools`, installation worked! Cheers :)

**Comment by RedFantom** [comment]
@ndv99 Glad it worked! If you have any other issues or ideas, even, feel free to open up another issue.
